name: 💬 General Feedback
description: Share thoughts, suggestions, or usage experiences
title: "[Feedback] "
labels: [feedback]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for using SPF Flattener! Whether you've got praise, pain points, or ideas, I'd love to hear them.

  - type: textarea
    id: experience
    attributes:
      label: What's Working Well?
      description: Share what you like or what's been helpful

  - type: textarea
    id: pain
    attributes:
      label: What Could Be Improved?
      description: Anything confusing, frustrating, or missing?

  - type: textarea
    id: ideas
    attributes:
      label: Suggestions or Ideas
      description: Optional—any features or improvements you'd like to see?
