name: 🌐 DNS Provider Integration Request
description: Request support for a new DNS provider
title: "[Provider] "
labels: [provider-request]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Want to use SPF Flattener with a DNS provider that's not yet supported? Let me know below.

  - type: input
    id: provider
    attributes:
      label: DNS Provider Name
      description: e.g., Cloudflare, Route53, Namecheap
    validations:
      required: true

  - type: textarea
    id: api
    attributes:
      label: API Documentation
      description: Link to the provider's API docs if available

  - type: textarea
    id: motivation
    attributes:
      label: Why This Provider?
      description: Share your use case or why this integration matters
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      description: Anything else that might help with implementation
